mysql:
  enabled: false
  host: localhost
  port: 3306
  db: database
  username: username
  password: password
  table: itemdrop
debug: false
pollDatabase: 1
fallbackCheckPeriod: 5
messages:
  delivered: '{BRIGHTGREEN}Recebeste %s %s!'
  dropped: '{BRIGHTGREEN}Wow! %s %s caiu perto de ti!'